packages:
  - '.'
  - 'gumroad-frontend'
  - 'gumroad-backend'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  vite: "6.3.5"

